build:
  stage: build
  script: gradle build
  

test:
  stage: test
  script: gradle test
  
quality:
  stage: test
  script: gradle sonarqube -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD

