image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


stages:
  - build
  - test
  - sonarqube-check

build:
  stage: build
  script: 
    - cd API
    - .\gradlew build
  

test:
  stage: test
  script: 
    - cd API
    - .\gradlew test


sonarqube-check:
  stage: sonarqube-check
 
    - cd API
    - .\gradlew sonarqube
  
