build:
  stage: build
  script: 
    - echo gradle build

  

test:
  stage: test
  script: 
    - echo gradle test

  
quality:
  stage: test
  script: 
    - echo gradle sonarqube -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD

